package com.guardbench.testrun.domain;

public enum TestExecutionErrorCode {
    TARGET_NOT_FOUND,
    TARGET_ACCESS_DENIED,
    TARGET_CONFIGURATION_INVALID,
    EVALUATOR_NOT_FOUND,
    EVALUATOR_ACCESS_DENIED,
    EVALUATOR_CONFIGURATION_INVALID,
    PROVIDER_UNAVAILABLE,
    PROVIDER_RESPONSE_INVALID,
    PROVIDER_TIMEOUT
}
